version: "3"

services:
  frontend:
    build: ./frontend
    depends_on:
      - backend
    ports:
      - 4200:4200
    volumes:
      - ./frontend:/app
    working_dir: /app

  database:
    image: postgres:13-alpine
    env_file: ./database/.env
    volumes:
      - ./database/data:/var/lib/postgresql/data

  backend:
    build: ./backend
    depends_on:
      - database
    env_file: ./backend/.env
    ports:
      - 3333:3333
    volumes:
      - ./backend:/app
    working_dir: /app
